### ISSUE TITLE
フォーマット処理の不具合に見える挙動に関する質問

### ISSUE THREAD

**Issue by tomohiko-ito-10antz** [tys-muta/go-err#7]
以下のコードで、`message`を含む文字列が表示されることを期待したのですが、`func (e *Error) FormatError(p xerrors.Printer) (next error)`が表示を行わないため、何も表示されません。この挙動は意図した通りのものでしょうか？

```go
package main

import (
	"fmt"

	"github.com/tys-muta/go-ers"
	"google.golang.org/grpc/codes"
)

func main() {
	code := codes.Internal
	reason := "reason"
	message := "message"
	err := ers.New(code, reason, message)

	fmt.Printf(`%v`, err) // empty string
}
```

**Comment by t-mutaguchi-10antz** [comment]
`%v` で簡易版スタックトレース、`%+v` で詳細なスタックトレースが出力される事が意図されてはいます。`%v` でメッセージ、`%+v` で詳細なスタックトレースを出力するように修正する事も可能です。簡易版スタックトレースは今まで必要となった事が無いので、出力しないようにしても良いかなと考えています。

ただ、Endpoints の仕様 ( `{code:xxx, message:xxx}` という 2 種の情報しか返せない ) に合わせる必要があったため、エラー時、クライアントにレスポンスする JSON は `{"code": {gRPC Status Code}, "message": "{ApplicationErrorCode}"}` となっており、ここの互換性は崩せないため、合わせてインターセプターにも手を加える必要がありそうです。

**Comment by tys-muta** [comment]
https://github.com/tys-muta/go-ers/pull/8
にて対応

**Comment by tys-muta** [comment]
https://github.com/tys-muta/go-ers/pull/8
にて対応
